server:
  port: 8080

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rcty?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: rcty
    password: Lk7K4kJtR2mXPY8w
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB